### ISSUE TITLE
Crashes everytime I open on Nexus 5 Android 5.1.1

### ISSUE THREAD

**Issue by benwoodman** [dotWee/MicroPinner#10]
Hey love the app however, ever since the most recent update, the app crashes as soon as I open it up. I'm not sure what's causing it, but it used to work perfecly. 

Nexus 5 
Android 5.1.1

**Comment by dotWee** [comment]
Are you be able to extract a logcat for me?

**Comment by dotWee** [comment]
Issue closed, should be fixed by commit 358e06846427b3b43f627bf8e9bc795bbaae475a.
