### ISSUE TITLE
Attributes lost on reboot

### ISSUE THREAD

**Issue by carmebar** [dotWee/MicroPinner#13]
After a reboot some attributes are lost.

Steps to reproduce:
- Create a notification with "persistent" or "show notification actions" enabled.
- Check that the notification works as expected.
- Reboot or _am broadcast -a android.intent.action.BOOT_COMPLETED_

- Now the notification has lost the custom attributes.

I've checked the database after rebooting and the parameters are properly stored.

On a Nexus 5 with Lineage OS 14

**Comment by carmebar** [comment]
It's a known bug:
https://issuetracker.google.com/issues/36969644

I've made a pull request with a workaround. Hope it's good enough to be merged 👍

**Comment by dotWee** [comment]
Thanks! Your pull request has been merged, this issue can be closed.
