### ISSUE TITLE
unable to pin notes using micro pinnner

### ISSUE THREAD

**Issue by kodeblacc** [dotWee/MicroPinner#17]
#### Expected behavior
I expected that I should be able to pin notes to my notifications panel as described by the app
#### Actual behavior
After doing the needful by creating a note and giving it it's title and doing all the necessary things, it doesn't pin when I click pin.

#### How to reproduce
- download micro pinner from google playstore
- launch the app
- turn the pinner service on
- make a note to pin
- press pin and it doesn't work

* Device:  infinix note 4
* Operating system: android 8.0
* software version: v2.1.0

#### Recording Of The Bug
https://vimeo.com/260664241
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@kodeblacc/unable-to-pin-notes-using-micro-pinnner">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by dotWee** [comment]
This issue is related to the new notification channel in Android Oreo and fixed with the just-released version v2.2.0. https://github.com/dotWee/MicroPinner/releases/tag/release-v2.2.0

**Comment by kodeblacc** [comment]
I'll go ahead and check it out.

I'll love to do copywriting on your project, this will include composing
and compiling FAQs, More detailed readme, privacy policy and About us
section.

I'll create pull requests for the following so you could merge them into
the master branch that's if you are interested.

**Comment by dotWee** [comment]
Sure, go ahead. I'm open for every contribution.

**Comment by kodeblacc** [comment]
Alright thanks. I'll start right away

**Comment by kodeblacc** [comment]
I just created a pull request for the update on readme.
