### ISSUE TITLE
New Design

### ISSUE THREAD

**Issue by ghost** [dotWee/MicroPinner#26]
![micro-pinner](https://user-images.githubusercontent.com/36993664/39593213-d1f0ce74-4f11-11e8-9ac1-1cbf105ed4ac.jpg)

Hi,

I have studied your work and I think a new design will make you more visible. I designed for you, I hope you like it and you want to use it. If you want to reach me, you can look at the my profile. I can give you all the formats of the design free. If you want a change please specify.

**Comment by dotWee** [comment]
Hey Yasujizr, thanks for your ideas! 

With this project I'm following Google's Material Design guidelines. Your designs are a bit off the references, but I'm open for other ideas. Take a look at them [here](https://material.io/guidelines/style/icons.html).

**Comment by ghost** [comment]
Hi @dotWee,

I designed a few examples. I hope you will like it.

![logomaterialdes gn](https://user-images.githubusercontent.com/36993664/39630661-a15053d2-4fb8-11e8-80d0-a3bbf105b46c.jpg)

**Comment by ghost** [comment]
![logomaterialdes gn](https://user-images.githubusercontent.com/36993664/39666273-bf3ef636-50a9-11e8-97fd-e9f9c4c3e37e.jpg)

@dotWee 

More 3D look and a new design. My favorite is on the right. What do you think?
