### ISSUE TITLE
Please move the tag for v2.2.0 to the commit with the correct gradle

### ISSUE THREAD

**Issue by IzzySoft** [dotWee/MicroPinner#28]
`build.gradle` has been set to the correct versionName/versionNumber only *after* the tag has been created – which is why F-Droid doesn't pick up the new version. Could you please "re-tag" accordingly? Thanks!

**Comment by dotWee** [comment]
Sure thing! Invalid tag position has been corrected. 

Could you please tell me if F-Droid can handle it now?

**Comment by licaon-kter** [comment]
This has been build, you can close.

**Comment by IzzySoft** [comment]
Thanks, @licaon-kter – closing then.
