### ISSUE TITLE
It would be really nice if the pins saved so they appeared after phone restart.

### ISSUE THREAD

**Issue by benwoodman** [dotWee/MicroPinner#3]
I would suggest adding a feature that allows the pins to be saved. I have made pins in the past, but they don't appear after I restart my phone. I know this would be a lot of work, but for me this is the difference in a good app and an amazing app that I use everyday.

**Comment by dotWee** [comment]
Shouldn't be that much work. I have the following idea:
1. Save pins state (Title, content, visibility & priority) after creation to SharedPreferences using a JSON-Array
2. Make use of notification-DeleteIntents to remove pins from the array
3. Use a BroadcastReceiver to receive _BOOT_COMPLETED_ intents and restore pins by parsing the JSON-Array

I'll try to get it this weekend running.

**Comment by dotWee** [comment]
Finished in version v1.5.
